[book]
title = "stint"
authors = ["Constantine Molchanov"]
language = "en"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 2

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/status-im/nim-stint/"
